# my_run.yaml
defaults:
  - ppo_trainer # 这里写 main_ppo.py 默认的 config_name（不带 .yaml）
  - _self_
reward_model:
  reward_manager: naive_api

debug: false
vs_debug: false

data:
  train_files:
    - /path/to/DeepEyes-Datasets-47k/data_0.1.2_visual_toolbox_v2.parquet
    - /path/to/DeepEyes-Datasets-47k/data_v0.8_visual_toolbox_v2.parquet
    - /path/to/DeepEyes-Datasets-47k/data_thinklite_reasoning_acc.parquet
    - /path/to/geollava8k_size12k_all_threads_0117_prompt_refinedv1_5.parquet
  val_files:
    - /path/to/geollava8k_size12k_all_threads_0117_prompt_refinedv1_5.parquet
  train_batch_size: 128
  max_prompt_length: 32768
  max_response_length: 16384
  return_raw_chat: true
  filter_overlong_prompts: false

algorithm:
  adv_estimator: grpo
  kl_ctrl:
    kl_coef: 0.001

actor_rollout_ref:
  model:
    enable_gradient_checkpointing: true
    path: /path/to/saves/Qwen2.5-VL-7B-Instruct/highrs_interleaved
    use_remove_padding: true

  actor:
    optim:
      lr: 5e-7
    ppo_mini_batch_size: 128
    ppo_micro_batch_size_per_gpu: 1
    use_kl_loss: false
    kl_loss_coef: 0.01
    kl_loss_type: low_var_kl
    entropy_coeff: 0.001
    checkpoint:
      contents: [model, hf_model, optimizer, extra]
    ulysses_sequence_parallel_size: 1
    fsdp_config:
      param_offload: true
      optimizer_offload: true

  rollout:
    log_prob_micro_batch_size_per_gpu: 16
    tensor_model_parallel_size: 1
    name: vllm
    n: 16
    max_num_batched_tokens: 20834
    gpu_memory_utilization: 0.6
    enforce_eager: false
    free_cache_engine: false
    enable_chunked_prefill: false

    agent:
      activate_agent: true
      tool_name_key: env_name
      single_response_max_tokens: 18198
      max_turns: 5
      concurrent_workers: 8
      show_tqdm: true

  ref:
    log_prob_micro_batch_size_per_gpu: 16
    fsdp_config:
      param_offload: true

trainer:
  critic_warmup: 4
  logger: [console, tensorboard]
  val_before_train: false
  n_gpus_per_node: 8
  nnodes: 4
  save_freq: 8
  test_freq: 10000
  project_name: deepgeollava
  experiment_name: 0126_debug_highrs_interleaved_promptv1_5_rerun_with_local_llm_check_l20_speed
  default_local_dir: /path/to/verl_ckpts/deepgeollava/0126_debug_highrs_interleaved_promptv1_5_rerun_with_local_llm_check_l20_speed
  tensorboard_dir: /path/to/verl_ckpts/logs/tensorboard
  rl_logging_board_dir: /path/to/verl_ckpts/logs/rl_logging_board
  total_epochs: 32
